//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.30 at 10:15:53 PM PDT 
//


package org.cote.example.objects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExampleCollectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExampleCollectionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.cote.org/example/objects}ExampleBaseType">
 *       &lt;sequence>
 *         &lt;element name="examples" type="{http://www.cote.org/example/objects}ExampleType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExampleCollectionType", propOrder = {
    "examples"
})
public class ExampleCollectionType
    extends ExampleBaseType
{

    protected List<ExampleType> examples;

    /**
     * Gets the value of the examples property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the examples property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExamples().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExampleType }
     * 
     * 
     */
    public List<ExampleType> getExamples() {
        if (examples == null) {
            examples = new ArrayList<ExampleType>();
        }
        return this.examples;
    }

}
