//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.30 at 10:15:53 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.cote.org/example/objects", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.cote.example.objects;
